apiVersion: apps/v1
kind: Deployment
metadata:
  name: trackingapp-backend
  labels:
    app: trackingapp-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trackingapp-backend
  template:
    metadata:
      labels:
        app: trackingapp-backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - trackingapp-frontend
            topologyKey: topology.kubernetes.io/zone
      containers:
      - name: trackingapp-backend
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        envFrom:
        - secretRef:
            name: postgres-db-config
        readinessProbe:
          httpGet:
            path: /api/server
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 10

#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: trackingapp-backend
#  labels:
#    app: trackingapp-backend
#spec:
#  selector:
#    app: trackingapp-backend
#  ports:
#    - name: server
#      protocol: TCP
#      port: 80
#      targetPort: 8082
#  type: ClusterIP
